"""update

Revision ID: 375a0f775edf
Revises: d0bdda8454ea
Create Date: 2024-02-14 20:52:47.370522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375a0f775edf'
down_revision: Union[str, None] = 'd0bdda8454ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('nm_id', sa.Integer(), nullable=True))
    op.drop_column('product_details', 'nmId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('nmId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('product_details', 'nm_id')
    # ### end Alembic commands ###
