"""update names

Revision ID: ddbd109e2435
Revises: 375a0f775edf
Create Date: 2024-02-14 21:45:53.870820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddbd109e2435'
down_revision: Union[str, None] = '375a0f775edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('productValuation', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('createdDate', sa.DateTime(), nullable=True))
    op.add_column('feedbacks', sa.Column('wasViewed', sa.Boolean(), nullable=True))
    op.add_column('feedbacks', sa.Column('photoLinks', sa.String(), nullable=True))
    op.add_column('feedbacks', sa.Column('userName', sa.String(), nullable=True))
    op.add_column('feedbacks', sa.Column('matchingSize', sa.String(), nullable=True))
    op.add_column('feedbacks', sa.Column('isAbleSupplierFeedbackValuation', sa.Boolean(), nullable=True))
    op.add_column('feedbacks', sa.Column('supplierFeedbackValuation', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('isAbleSupplierProductValuation', sa.Boolean(), nullable=True))
    op.add_column('feedbacks', sa.Column('supplierProductValuation', sa.Integer(), nullable=True))
    op.add_column('feedbacks', sa.Column('isAbleReturnProductOrders', sa.Boolean(), nullable=True))
    op.add_column('feedbacks', sa.Column('returnProductOrdersDate', sa.DateTime(), nullable=True))
    op.add_column('feedbacks', sa.Column('productDetailId', sa.Integer(), nullable=True))
    op.drop_constraint('feedbacks_product_detail_id_fkey', 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'product_details', ['productDetailId'], ['id'])
    op.drop_column('feedbacks', 'product_detail_id')
    op.drop_column('feedbacks', 'is_able_supplier_feedback_valuation')
    op.drop_column('feedbacks', 'user_name')
    op.drop_column('feedbacks', 'created_date')
    op.drop_column('feedbacks', 'photo_links')
    op.drop_column('feedbacks', 'was_viewed')
    op.drop_column('feedbacks', 'is_able_return_product_orders')
    op.drop_column('feedbacks', 'is_able_supplier_product_valuation')
    op.drop_column('feedbacks', 'supplier_feedback_valuation')
    op.drop_column('feedbacks', 'supplier_product_valuation')
    op.drop_column('feedbacks', 'matching_size')
    op.drop_column('feedbacks', 'return_product_orders_date')
    op.drop_column('feedbacks', 'product_valuation')
    op.add_column('product_details', sa.Column('imtId', sa.Integer(), nullable=True))
    op.add_column('product_details', sa.Column('nmId', sa.Integer(), nullable=True))
    op.add_column('product_details', sa.Column('productName', sa.String(), nullable=True))
    op.add_column('product_details', sa.Column('supplierArticle', sa.String(), nullable=True))
    op.add_column('product_details', sa.Column('supplierName', sa.String(), nullable=True))
    op.add_column('product_details', sa.Column('brandName', sa.String(), nullable=True))
    op.drop_column('product_details', 'supplier_name')
    op.drop_column('product_details', 'nm_id')
    op.drop_column('product_details', 'brand_name')
    op.drop_column('product_details', 'product_name')
    op.drop_column('product_details', 'supplier_article')
    op.drop_column('product_details', 'imt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_details', sa.Column('imt_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('supplier_article', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('product_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('nm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_details', sa.Column('supplier_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product_details', 'brandName')
    op.drop_column('product_details', 'supplierName')
    op.drop_column('product_details', 'supplierArticle')
    op.drop_column('product_details', 'productName')
    op.drop_column('product_details', 'nmId')
    op.drop_column('product_details', 'imtId')
    op.add_column('feedbacks', sa.Column('product_valuation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('return_product_orders_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('matching_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('supplier_product_valuation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('supplier_feedback_valuation', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('is_able_supplier_product_valuation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('is_able_return_product_orders', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('was_viewed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('photo_links', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('is_able_supplier_feedback_valuation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('product_detail_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key('feedbacks_product_detail_id_fkey', 'feedbacks', 'product_details', ['product_detail_id'], ['id'])
    op.drop_column('feedbacks', 'productDetailId')
    op.drop_column('feedbacks', 'returnProductOrdersDate')
    op.drop_column('feedbacks', 'isAbleReturnProductOrders')
    op.drop_column('feedbacks', 'supplierProductValuation')
    op.drop_column('feedbacks', 'isAbleSupplierProductValuation')
    op.drop_column('feedbacks', 'supplierFeedbackValuation')
    op.drop_column('feedbacks', 'isAbleSupplierFeedbackValuation')
    op.drop_column('feedbacks', 'matchingSize')
    op.drop_column('feedbacks', 'userName')
    op.drop_column('feedbacks', 'photoLinks')
    op.drop_column('feedbacks', 'wasViewed')
    op.drop_column('feedbacks', 'createdDate')
    op.drop_column('feedbacks', 'productValuation')
    # ### end Alembic commands ###
