"""current update

Revision ID: e24ef7a04548
Revises: f9a705bfd66c
Create Date: 2024-02-19 09:13:39.507647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24ef7a04548'
down_revision: Union[str, None] = 'f9a705bfd66c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_mapping',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marketplace_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internal_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('external_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='products_mapping_pkey'),
    sa.UniqueConstraint('external_code', name='products_mapping_external_code_key')
    )
    # ### end Alembic commands ###
