"""delete some dict columns

Revision ID: f9a705bfd66c
Revises: ddbd109e2435
Create Date: 2024-02-16 09:43:54.421931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a705bfd66c'
down_revision: Union[str, None] = 'ddbd109e2435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'answer')
    op.drop_column('feedbacks', 'photoLinks')
    op.drop_column('feedbacks', 'video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('photoLinks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
